pub mod request;

use std::sync::{Arc, RwLock};

use tokio::sync::mpsc::{UnboundedReceiver, UnboundedSender};
use tokio::task::JoinHandle;

use crate::autocomplete::{CachedColumn, CachedTable, SchemaCache};
use crate::datasource::{
    CatalogInfo, ColumnInfo, Datasource, DatasourceError, IndexInfo, QueryResult, SchemaInfo,
    TableInfo,
};
use crate::log::Logger;
pub use request::{RequestCounter, RequestId};

#[derive(Debug)]
pub enum WorkerCommand {
    Execute {
        req: RequestId,
        sql: String,
    },
    Cancel,
    /// Roll back any open transaction on the pinned session
    /// connection and drop it. The next `Execute` re-acquires from
    /// the pool. Fired by the user-facing `:reset` and `:clear`
    /// commands.
    ResetSession,
    Introspect {
        target: IntrospectTarget,
    },
    /// Open a new connection. On success the worker swaps its active
    /// datasource (the previous one, if any, is dropped — its sqlx pool
    /// closes on drop).
    Connect {
        name: String,
        url: String,
    },
    /// Eagerly populate the autocomplete `SchemaCache` for the active
    /// connection. Phase 1 prime: default schema + catalogs + schemas of
    /// the default catalog + tables of the default schema. Columns are
    /// loaded lazily by `LoadCompletionColumns`.
    PrimeCompletionCache {
        connection: String,
    },
    /// Drop the autocomplete cache and re-prime. User-facing as
    /// `:reload`. Cheap: same path as the connect prime.
    Reload {
        connection: String,
    },
    /// Lazy column load. Fired when the engine references a table
    /// whose columns aren't in the cache yet — typically the first
    /// time a user types `<table>.` or qualifies into a not-yet-seen
    /// table.
    LoadCompletionColumns {
        catalog: String,
        schema: String,
        table: String,
    },
    Close,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IntrospectTarget {
    Catalogs,
    Schemas {
        catalog: String,
    },
    Tables {
        catalog: String,
        schema: String,
    },
    Columns {
        catalog: String,
        schema: String,
        table: String,
    },
    Indices {
        catalog: String,
        schema: String,
        table: String,
    },
}

#[derive(Debug)]
pub enum WorkerEvent {
    QueryDone {
        req: RequestId,
        result: QueryResult,
    },
    QueryFailed {
        req: RequestId,
        error: DatasourceError,
    },
    SchemaLoaded {
        target: IntrospectTarget,
        payload: SchemaPayload,
    },
    SchemaFailed {
        target: IntrospectTarget,
        error: DatasourceError,
    },
    Connected {
        name: String,
    },
    ConnectFailed {
        name: String,
        error: DatasourceError,
    },
    /// Result of a one-shot `TestConnection` fired from the connection
    /// form. The active datasource is NOT swapped; success just means
    /// the URL accepted a connect-then-drop handshake.
    TestConnectionResult {
        success: bool,
        error: Option<String>,
    },
    /// Cache prime stage finished. The data is already written into the
    /// shared `SchemaCache`; this event is purely a signal so the UI can
    /// re-render the popover (and a future schema panel) when fresh
    /// data lands.
    CompletionCacheStage {
        stage: CacheStage,
    },
    CompletionCacheFailed {
        stage: CacheStage,
        error: DatasourceError,
    },
    /// Streaming delta from an LLM chat turn. Generated by the
    /// short-lived task spawned in `crate::llm::worker::spawn_chat_turn`,
    /// not by the long-running `worker::run` loop.
    ChatDelta(crate::llm::worker::ChatDelta),
    /// LLM has emitted a tool call. The worker is awaiting a reply with
    /// the JSON-encoded result so it can feed the result back to the
    /// model and continue the turn. Handled on the UI thread because
    /// most tools touch `app.editor` or `app.schema_cache`.
    ChatToolRequest {
        call_id: String,
        name: String,
        args_json: String,
        reply: tokio::sync::oneshot::Sender<crate::llm::worker::ToolReply>,
    },
    /// A filesystem read tool finished off-thread (via
    /// `tokio::task::spawn_blocking`). The spawned task already replied
    /// to the LLM oneshot — this event exists purely to update the
    /// chat panel's tool-result block from the main loop, which owns
    /// `app.chat`. `agents_md_loaded` carries the relative-path
    /// headers (e.g. `src/llm/AGENTS.md`) of any AGENTS.md files the
    /// fs tool's directory walk discovered, so the main loop can
    /// surface a per-load chat notice.
    ChatFsToolDone {
        call_id: String,
        name: String,
        display: String,
        error: Option<String>,
        agents_md_loaded: Vec<String>,
    },
    /// Background update check found a newer release. UI shows the
    /// "y/n" prompt.
    UpdateAvailable {
        current: String,
        latest: String,
    },
    /// Install script exited 0 — surface a notice telling the user to
    /// restart rowdy.
    UpdateInstalled {
        tag: String,
    },
    /// Install script failed (non-zero exit). The string is the first
    /// stderr line, suitable for the bottom-bar `Failed` status.
    UpdateInstallFailed {
        error: String,
    },
    /// `:update` finished and we're already on the latest release —
    /// surface a notice so the user knows the check happened.
    UpdateUpToDate {
        current: String,
    },
    /// `:update` failed to talk to GitHub (network, JSON, etc.).
    /// Distinct from `UpdateInstallFailed` so the bottom-bar copy can
    /// say "update check failed" vs "update failed".
    UpdateCheckFailed {
        error: String,
    },
}

/// Phase markers for cache prime / lazy loads. `Tables` carries the
/// (catalog, schema) so the UI can scope its re-render; `Columns`
/// carries the table identity so the popover can decide whether the
/// fresh data matches its current qualifier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CacheStage {
    DefaultSchema,
    Catalogs,
    Schemas {
        catalog: String,
    },
    Tables {
        catalog: String,
        schema: String,
    },
    Columns {
        catalog: String,
        schema: String,
        table: String,
    },
    Reloaded,
}

#[derive(Debug)]
pub enum SchemaPayload {
    Catalogs(Vec<CatalogInfo>),
    Schemas(Vec<SchemaInfo>),
    Tables(Vec<TableInfo>),
    Columns(Vec<ColumnInfo>),
    Indices(Vec<IndexInfo>),
}

/// Runs until either the command channel closes or `Close` is received.
/// Starts with no active datasource — the App is expected to send `Connect`
/// once the user has chosen one.
pub async fn run(
    logger: Logger,
    mut commands: UnboundedReceiver<WorkerCommand>,
    events: UnboundedSender<WorkerEvent>,
    cache: Arc<RwLock<SchemaCache>>,
) {
    let mut datasource: Option<Arc<dyn Datasource>> = None;
    let mut current_query: Option<JoinHandle<()>> = None;

    while let Some(cmd) = commands.recv().await {
        match cmd {
            WorkerCommand::Close => break,
            WorkerCommand::Connect { name, url } => {
                handle_connect(&logger, &events, &mut datasource, name, url).await;
            }
            WorkerCommand::Cancel => match &datasource {
                Some(ds) => cancel_query(&logger, ds.as_ref(), &mut current_query).await,
                None => logger.warn("worker", "cancel ignored: no active connection"),
            },
            WorkerCommand::ResetSession => match &datasource {
                Some(ds) => {
                    if let Err(e) = ds.reset_session().await {
                        logger.warn("worker", format!("reset failed: {e}"));
                    }
                }
                None => logger.warn("worker", "reset ignored: no active connection"),
            },
            WorkerCommand::Execute { req, sql } => match &datasource {
                Some(ds) => spawn_query(ds, &events, &mut current_query, req, sql),
                None => {
                    let _ = events.send(WorkerEvent::QueryFailed {
                        req,
                        error: DatasourceError::Connect("no active connection".into()),
                    });
                }
            },
            WorkerCommand::Introspect { target } => match &datasource {
                Some(ds) => spawn_introspect(ds, &events, target),
                None => {
                    let _ = events.send(WorkerEvent::SchemaFailed {
                        target,
                        error: DatasourceError::Connect("no active connection".into()),
                    });
                }
            },
            WorkerCommand::PrimeCompletionCache { connection } => match &datasource {
                Some(ds) => spawn_prime_cache(ds, &events, cache.clone(), connection, false),
                None => logger.warn("worker", "prime ignored: no active connection"),
            },
            WorkerCommand::Reload { connection } => match &datasource {
                Some(ds) => spawn_prime_cache(ds, &events, cache.clone(), connection, true),
                None => logger.warn("worker", "reload ignored: no active connection"),
            },
            WorkerCommand::LoadCompletionColumns {
                catalog,
                schema,
                table,
            } => match &datasource {
                Some(ds) => {
                    spawn_load_columns(ds, &events, cache.clone(), catalog, schema, table);
                }
                None => logger.warn("worker", "column load ignored: no active connection"),
            },
        }
    }
}

async fn handle_connect(
    logger: &Logger,
    events: &UnboundedSender<WorkerEvent>,
    current: &mut Option<Arc<dyn Datasource>>,
    name: String,
    url: String,
) {
    logger.info("worker", format!("connect to {name}"));
    match crate::datasource::connect(&url, logger.clone()).await {
        Ok(new_ds) => {
            // Drop the previous datasource — sqlx's pool closes on drop. We
            // can't call `Datasource::close` on an `Arc<dyn …>` cleanly, and
            // nothing today depends on graceful close.
            *current = Some(Arc::from(new_ds));
            let _ = events.send(WorkerEvent::Connected { name });
        }
        Err(error) => {
            logger.warn("worker", format!("connect failed: {error}"));
            let _ = events.send(WorkerEvent::ConnectFailed { name, error });
        }
    }
}

async fn cancel_query(
    logger: &Logger,
    datasource: &dyn Datasource,
    current: &mut Option<JoinHandle<()>>,
) {
    // Hit the server cancel first so the in-flight query's pinned connection
    // returns a "canceled" error of its own. Awaiting here also serializes
    // against the next command — no follow-up `Execute` can start and
    // overwrite the in-flight identifier before `cancel()` reads it.
    if let Err(e) = datasource.cancel().await {
        logger.warn("worker", format!("cancel failed: {e}"));
    }
    // Belt-and-braces: if the spawn_query future hasn't already finished
    // off the cancel error, drop it now so its pooled connection is freed.
    if let Some(handle) = current.take() {
        handle.abort();
    }
}

fn spawn_query(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    current: &mut Option<JoinHandle<()>>,
    req: RequestId,
    sql: String,
) {
    if let Some(prev) = current.take() {
        prev.abort();
    }
    let datasource = datasource.clone();
    let events = events.clone();
    *current = Some(tokio::spawn(async move {
        let event = handle_execute_multi(datasource.as_ref(), req, sql).await;
        let _ = events.send(event);
    }));
}

fn spawn_introspect(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    target: IntrospectTarget,
) {
    let datasource = datasource.clone();
    let events = events.clone();
    tokio::spawn(async move {
        let event = handle_introspect(datasource.as_ref(), target).await;
        let _ = events.send(event);
    });
}

/// Splits `sql` on top-level `;` and runs each statement sequentially on
/// the datasource's pinned session connection, so a leading `BEGIN`
/// (or `START TRANSACTION`) really does scope subsequent DML on the
/// same backend. Stops at the first failure — remaining statements are
/// skipped so a broken script doesn't keep modifying state past the
/// error.
///
/// Emits a single `QueryDone` that carries the *last* statement's
/// columns/rows (intermediate row sets are dropped — stacked results
/// are a separate roadmap item) plus a `statements_run` count and a
/// summed `affected` across DML statements.
async fn handle_execute_multi(
    datasource: &dyn Datasource,
    req: RequestId,
    sql: String,
) -> WorkerEvent {
    let pieces = crate::datasource::sql::split_statements(&sql);
    if pieces.is_empty() {
        // Whole input was empty / whitespace / bare `;`s. Treat as a
        // single empty execute so the existing UX (status flips to
        // "ok: 0 rows") is preserved.
        return match datasource.execute(&sql).await {
            Ok(result) => WorkerEvent::QueryDone { req, result },
            Err(error) => WorkerEvent::QueryFailed { req, error },
        };
    }

    let total = pieces.len();
    let mut last: Option<crate::datasource::QueryResult> = None;
    let mut summed_affected: Option<u64> = None;
    let mut total_elapsed = std::time::Duration::ZERO;
    let mut ran = 0usize;
    for piece in &pieces {
        match datasource.execute(piece).await {
            Ok(r) => {
                ran += 1;
                if let Some(a) = r.affected {
                    summed_affected = Some(summed_affected.unwrap_or(0) + a);
                }
                total_elapsed += r.elapsed;
                last = Some(r);
            }
            Err(error) => {
                let msg = if total > 1 {
                    crate::datasource::DatasourceError::Execute(format!(
                        "statement {} of {total} failed: {error}",
                        ran + 1
                    ))
                } else {
                    error
                };
                return WorkerEvent::QueryFailed { req, error: msg };
            }
        }
    }

    let mut result = last.expect("at least one piece ran");
    result.statements_run = ran;
    result.elapsed = total_elapsed;
    // If the final statement returned rows, keep its own affected
    // (None for SELECTs). Only roll the sum forward when the last
    // statement is DML — that's the case where the user wants to see
    // "10 affected" across a multi-INSERT script.
    if result.columns.is_empty() {
        result.affected = summed_affected;
    }
    WorkerEvent::QueryDone { req, result }
}

fn spawn_load_columns(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    cache: Arc<RwLock<SchemaCache>>,
    catalog: String,
    schema: String,
    table: String,
) {
    let datasource = datasource.clone();
    let events = events.clone();
    tokio::spawn(async move {
        load_columns(datasource.as_ref(), &events, &cache, catalog, schema, table).await;
    });
}

async fn load_columns(
    datasource: &dyn Datasource,
    events: &UnboundedSender<WorkerEvent>,
    cache: &RwLock<SchemaCache>,
    catalog: String,
    schema: String,
    table: String,
) {
    // If another caller already populated this entry while we were
    // queued, skip the round-trip. The check is racy (a second
    // identical load could still get through), but the worst case is a
    // duplicated read — acceptable for an autocomplete prime.
    if let Ok(guard) = cache.read()
        && guard
            .columns
            .contains_key(&(catalog.clone(), schema.clone(), table.clone()))
    {
        return;
    }
    match datasource
        .introspect_columns(&catalog, &schema, &table)
        .await
    {
        Ok(cols) => {
            let cached: Vec<CachedColumn> = cols
                .into_iter()
                .map(|c| CachedColumn {
                    name: c.name,
                    type_name: c.type_name,
                })
                .collect();
            if let Ok(mut guard) = cache.write() {
                guard
                    .columns
                    .insert((catalog.clone(), schema.clone(), table.clone()), cached);
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Columns {
                    catalog,
                    schema,
                    table,
                },
            });
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::Columns {
                    catalog,
                    schema,
                    table,
                },
                error,
            });
        }
    }
}

fn spawn_prime_cache(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    cache: Arc<RwLock<SchemaCache>>,
    connection: String,
    is_reload: bool,
) {
    let datasource = datasource.clone();
    let events = events.clone();
    tokio::spawn(async move {
        prime_cache(datasource.as_ref(), &events, &cache, connection, is_reload).await;
    });
}

/// Phase 1 cache prime: default schema + catalogs + schemas of the
/// default catalog + tables of the default schema. Each step writes its
/// result into the shared cache and emits a `CompletionCacheStage`
/// event. Failures are logged via `CompletionCacheFailed` but don't
/// abort later stages — partial data is more useful than none.
async fn prime_cache(
    datasource: &dyn Datasource,
    events: &UnboundedSender<WorkerEvent>,
    cache: &RwLock<SchemaCache>,
    connection: String,
    is_reload: bool,
) {
    if is_reload && let Ok(mut guard) = cache.write() {
        guard.clear();
    }

    // Stage 1: default schema. If this fails we still try the rest, but
    // unqualified contexts won't have anywhere to look.
    let default = match datasource.default_schema().await {
        Ok(d) => {
            if let Ok(mut guard) = cache.write() {
                guard.connection = Some(connection.clone());
                guard.default_catalog = Some(d.catalog.clone());
                guard.default_schema = Some(d.schema.clone());
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::DefaultSchema,
            });
            Some(d)
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::DefaultSchema,
                error,
            });
            None
        }
    };

    // Stage 2: catalogs.
    match datasource.introspect_catalogs().await {
        Ok(catalogs) => {
            if let Ok(mut guard) = cache.write() {
                guard.catalogs = catalogs.iter().map(|c| c.name.clone()).collect();
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Catalogs,
            });
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::Catalogs,
                error,
            });
        }
    }

    // Stage 3+4 only run if we know where to look.
    let Some(default) = default else {
        if is_reload {
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Reloaded,
            });
        }
        return;
    };

    // Stage 3: schemas of the default catalog.
    match datasource.introspect_schemas(&default.catalog).await {
        Ok(schemas) => {
            if let Ok(mut guard) = cache.write() {
                guard.schemas.insert(
                    default.catalog.clone(),
                    schemas.iter().map(|s| s.name.clone()).collect(),
                );
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Schemas {
                    catalog: default.catalog.clone(),
                },
            });
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::Schemas {
                    catalog: default.catalog.clone(),
                },
                error,
            });
        }
    }

    // Stage 4: tables of the default schema. (Columns are lazy.)
    if !default.schema.is_empty() {
        match datasource
            .introspect_tables(&default.catalog, &default.schema)
            .await
        {
            Ok(tables) => {
                let cached: Vec<CachedTable> = tables
                    .into_iter()
                    .map(|t| CachedTable {
                        name: t.name,
                        kind: t.kind,
                    })
                    .collect();
                if let Ok(mut guard) = cache.write() {
                    guard
                        .tables
                        .insert((default.catalog.clone(), default.schema.clone()), cached);
                }
                let _ = events.send(WorkerEvent::CompletionCacheStage {
                    stage: CacheStage::Tables {
                        catalog: default.catalog.clone(),
                        schema: default.schema.clone(),
                    },
                });
            }
            Err(error) => {
                let _ = events.send(WorkerEvent::CompletionCacheFailed {
                    stage: CacheStage::Tables {
                        catalog: default.catalog.clone(),
                        schema: default.schema.clone(),
                    },
                    error,
                });
            }
        }
    }

    if is_reload {
        let _ = events.send(WorkerEvent::CompletionCacheStage {
            stage: CacheStage::Reloaded,
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::log::Logger;
    use std::sync::{Arc, RwLock};
    use std::time::Duration;
    use tokio::sync::mpsc::unbounded_channel;

    fn fixture() -> (
        UnboundedSender<WorkerCommand>,
        UnboundedReceiver<WorkerEvent>,
        Arc<RwLock<SchemaCache>>,
        tokio::task::JoinHandle<()>,
    ) {
        let logger = Logger::discard();
        let (cmd_tx, cmd_rx) = unbounded_channel::<WorkerCommand>();
        let (evt_tx, evt_rx) = unbounded_channel::<WorkerEvent>();
        let cache = Arc::new(RwLock::new(SchemaCache::default()));
        let cache_for_run = cache.clone();
        let handle = tokio::spawn(async move {
            run(logger, cmd_rx, evt_tx, cache_for_run).await;
        });
        (cmd_tx, evt_rx, cache, handle)
    }

    /// Pull the next event off the receiver with a generous timeout so a hung
    /// worker fails the test instead of stalling CI forever.
    async fn next_event(rx: &mut UnboundedReceiver<WorkerEvent>) -> WorkerEvent {
        tokio::time::timeout(Duration::from_secs(5), rx.recv())
            .await
            .expect("worker did not send an event in time")
            .expect("worker dropped event channel before sending")
    }

    #[tokio::test]
    async fn worker_exits_cleanly_on_close_command() {
        let (cmd_tx, _evt_rx, _cache, handle) = fixture();
        cmd_tx.send(WorkerCommand::Close).expect("send Close");
        tokio::time::timeout(Duration::from_secs(2), handle)
            .await
            .expect("worker did not exit after Close")
            .expect("worker task panicked");
    }

    #[tokio::test]
    async fn worker_exits_when_command_channel_drops() {
        // No Close — just drop the sender. The recv loop should fall through.
        let (cmd_tx, _evt_rx, _cache, handle) = fixture();
        drop(cmd_tx);
        tokio::time::timeout(Duration::from_secs(2), handle)
            .await
            .expect("worker did not exit after channel drop")
            .expect("worker task panicked");
    }

    #[tokio::test]
    async fn cancel_without_connection_does_not_panic() {
        let (cmd_tx, mut evt_rx, _cache, handle) = fixture();
        cmd_tx.send(WorkerCommand::Cancel).expect("send Cancel");
        // No event is emitted (warn-only). Follow up with Close to drain.
        cmd_tx.send(WorkerCommand::Close).expect("send Close");
        handle.await.expect("worker task panicked");
        // The receiver should be empty (Cancel emits nothing).
        assert!(evt_rx.try_recv().is_err());
    }

    #[tokio::test]
    async fn execute_without_connection_emits_query_failed() {
        let (cmd_tx, mut evt_rx, _cache, handle) = fixture();
        let req = RequestId(42);
        cmd_tx
            .send(WorkerCommand::Execute {
                req,
                sql: "SELECT 1".into(),
            })
            .expect("send Execute");
        match next_event(&mut evt_rx).await {
            WorkerEvent::QueryFailed { req: got, error } => {
                assert_eq!(got, req);
                assert!(
                    matches!(error, DatasourceError::Connect(_)),
                    "expected Connect error, got {error:?}",
                );
            }
            other => panic!("expected QueryFailed, got {other:?}"),
        }
        cmd_tx.send(WorkerCommand::Close).ok();
        handle.await.ok();
    }

    #[tokio::test]
    async fn introspect_without_connection_emits_schema_failed() {
        let (cmd_tx, mut evt_rx, _cache, handle) = fixture();
        cmd_tx
            .send(WorkerCommand::Introspect {
                target: IntrospectTarget::Catalogs,
            })
            .expect("send Introspect");
        match next_event(&mut evt_rx).await {
            WorkerEvent::SchemaFailed { target, error } => {
                assert_eq!(target, IntrospectTarget::Catalogs);
                assert!(matches!(error, DatasourceError::Connect(_)));
            }
            other => panic!("expected SchemaFailed, got {other:?}"),
        }
        cmd_tx.send(WorkerCommand::Close).ok();
        handle.await.ok();
    }

    #[tokio::test]
    async fn connect_then_execute_sqlite_emits_query_done() {
        let (cmd_tx, mut evt_rx, _cache, handle) = fixture();
        cmd_tx
            .send(WorkerCommand::Connect {
                name: "mem".into(),
                url: "sqlite::memory:".into(),
            })
            .expect("send Connect");
        match next_event(&mut evt_rx).await {
            WorkerEvent::Connected { name } => assert_eq!(name, "mem"),
            other => panic!("expected Connected, got {other:?}"),
        }

        let req = RequestId(1);
        cmd_tx
            .send(WorkerCommand::Execute {
                req,
                sql: "SELECT 1 AS one".into(),
            })
            .expect("send Execute");
        match next_event(&mut evt_rx).await {
            WorkerEvent::QueryDone { req: got, result } => {
                assert_eq!(got, req);
                assert_eq!(result.columns.len(), 1);
                assert_eq!(result.rows.len(), 1);
            }
            other => panic!("expected QueryDone, got {other:?}"),
        }
        cmd_tx.send(WorkerCommand::Close).ok();
        handle.await.ok();
    }

    #[tokio::test]
    async fn connect_failure_emits_connect_failed() {
        let (cmd_tx, mut evt_rx, _cache, handle) = fixture();
        cmd_tx
            .send(WorkerCommand::Connect {
                name: "broken".into(),
                url: "totally-not-a-real-url".into(),
            })
            .expect("send Connect");
        match next_event(&mut evt_rx).await {
            WorkerEvent::ConnectFailed { name, .. } => assert_eq!(name, "broken"),
            other => panic!("expected ConnectFailed, got {other:?}"),
        }
        cmd_tx.send(WorkerCommand::Close).ok();
        handle.await.ok();
    }

    #[tokio::test]
    async fn prime_completion_cache_populates_schema_cache() {
        let (cmd_tx, mut evt_rx, cache, handle) = fixture();
        cmd_tx
            .send(WorkerCommand::Connect {
                name: "mem".into(),
                url: "sqlite::memory:".into(),
            })
            .expect("send Connect");
        // Drain the Connected event.
        next_event(&mut evt_rx).await;

        // `Reload` emits the terminal `Reloaded` stage that signals the
        // prime is done; `PrimeCompletionCache` walks the same stages but
        // doesn't emit a terminal marker.
        cmd_tx
            .send(WorkerCommand::Reload {
                connection: "mem".into(),
            })
            .expect("send Reload");
        // Spin until we see the terminal Reloaded stage (or timeout in
        // next_event). Other stages may arrive first; ignore them.
        let mut saw_reloaded = false;
        for _ in 0..16 {
            match next_event(&mut evt_rx).await {
                WorkerEvent::CompletionCacheStage {
                    stage: CacheStage::Reloaded,
                } => {
                    saw_reloaded = true;
                    break;
                }
                _ => continue,
            }
        }
        assert!(saw_reloaded, "expected CacheStage::Reloaded");

        // Default sqlite database has one schema named "main".
        let cache = cache.read().unwrap();
        assert!(
            cache.schemas.values().any(|v| v.iter().any(|s| s == "main")),
            "expected 'main' schema in primed cache; got {:?}",
            cache.schemas,
        );
        drop(cache);

        cmd_tx.send(WorkerCommand::Close).ok();
        handle.await.ok();
    }

    #[tokio::test]
    async fn reset_session_without_connection_does_not_panic() {
        let (cmd_tx, mut evt_rx, _cache, handle) = fixture();
        cmd_tx
            .send(WorkerCommand::ResetSession)
            .expect("send ResetSession");
        cmd_tx.send(WorkerCommand::Close).expect("send Close");
        handle.await.expect("worker task panicked");
        assert!(evt_rx.try_recv().is_err());
    }
}

async fn handle_introspect(datasource: &dyn Datasource, target: IntrospectTarget) -> WorkerEvent {
    let outcome = match &target {
        IntrospectTarget::Catalogs => datasource
            .introspect_catalogs()
            .await
            .map(SchemaPayload::Catalogs),
        IntrospectTarget::Schemas { catalog } => datasource
            .introspect_schemas(catalog)
            .await
            .map(SchemaPayload::Schemas),
        IntrospectTarget::Tables { catalog, schema } => datasource
            .introspect_tables(catalog, schema)
            .await
            .map(SchemaPayload::Tables),
        IntrospectTarget::Columns {
            catalog,
            schema,
            table,
        } => datasource
            .introspect_columns(catalog, schema, table)
            .await
            .map(SchemaPayload::Columns),
        IntrospectTarget::Indices {
            catalog,
            schema,
            table,
        } => datasource
            .introspect_indices(catalog, schema, table)
            .await
            .map(SchemaPayload::Indices),
    };
    match outcome {
        Ok(payload) => WorkerEvent::SchemaLoaded { target, payload },
        Err(error) => WorkerEvent::SchemaFailed { target, error },
    }
}
