pub mod request;

use std::sync::{Arc, RwLock};

use tokio::sync::mpsc::{UnboundedReceiver, UnboundedSender};
use tokio::task::JoinHandle;

use crate::autocomplete::{CachedColumn, CachedTable, SchemaCache};
use crate::datasource::{
    CatalogInfo, ColumnInfo, Datasource, DatasourceError, IndexInfo, QueryResult, SchemaInfo,
    TableInfo,
};
use crate::log::Logger;
pub use request::{RequestCounter, RequestId};

#[derive(Debug)]
pub enum WorkerCommand {
    Execute {
        req: RequestId,
        sql: String,
    },
    Cancel,
    Introspect {
        target: IntrospectTarget,
    },
    /// Open a new connection. On success the worker swaps its active
    /// datasource (the previous one, if any, is dropped — its sqlx pool
    /// closes on drop).
    Connect {
        name: String,
        url: String,
    },
    /// Eagerly populate the autocomplete `SchemaCache` for the active
    /// connection. Phase 1 prime: default schema + catalogs + schemas of
    /// the default catalog + tables of the default schema. Columns are
    /// loaded lazily by `LoadCompletionColumns`.
    PrimeCompletionCache {
        connection: String,
    },
    /// Drop the autocomplete cache and re-prime. User-facing as
    /// `:reload`. Cheap: same path as the connect prime.
    Reload {
        connection: String,
    },
    /// Lazy column load. Fired when the engine references a table
    /// whose columns aren't in the cache yet — typically the first
    /// time a user types `<table>.` or qualifies into a not-yet-seen
    /// table.
    LoadCompletionColumns {
        catalog: String,
        schema: String,
        table: String,
    },
    Close,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum IntrospectTarget {
    Catalogs,
    Schemas {
        catalog: String,
    },
    Tables {
        catalog: String,
        schema: String,
    },
    Columns {
        catalog: String,
        schema: String,
        table: String,
    },
    Indices {
        catalog: String,
        schema: String,
        table: String,
    },
}

#[derive(Debug)]
pub enum WorkerEvent {
    QueryDone {
        req: RequestId,
        result: QueryResult,
    },
    QueryFailed {
        req: RequestId,
        error: DatasourceError,
    },
    SchemaLoaded {
        target: IntrospectTarget,
        payload: SchemaPayload,
    },
    SchemaFailed {
        target: IntrospectTarget,
        error: DatasourceError,
    },
    Connected {
        name: String,
    },
    ConnectFailed {
        name: String,
        error: DatasourceError,
    },
    /// Cache prime stage finished. The data is already written into the
    /// shared `SchemaCache`; this event is purely a signal so the UI can
    /// re-render the popover (and a future schema panel) when fresh
    /// data lands.
    CompletionCacheStage {
        stage: CacheStage,
    },
    CompletionCacheFailed {
        stage: CacheStage,
        error: DatasourceError,
    },
    /// Streaming delta from an LLM chat turn. Generated by the
    /// short-lived task spawned in `crate::llm::worker::spawn_chat_turn`,
    /// not by the long-running `worker::run` loop.
    ChatDelta(crate::llm::worker::ChatDelta),
    /// LLM has emitted a tool call. The worker is awaiting a reply with
    /// the JSON-encoded result so it can feed the result back to the
    /// model and continue the turn. Handled on the UI thread because
    /// most tools touch `app.editor` or `app.schema_cache`.
    ChatToolRequest {
        call_id: String,
        name: String,
        args_json: String,
        reply: tokio::sync::oneshot::Sender<crate::llm::worker::ToolReply>,
    },
    /// Background update check found a newer release. UI shows the
    /// "y/n" prompt.
    UpdateAvailable {
        current: String,
        latest: String,
    },
    /// Install script exited 0 — surface a notice telling the user to
    /// restart rowdy.
    UpdateInstalled {
        tag: String,
    },
    /// Install script failed (non-zero exit). The string is the first
    /// stderr line, suitable for the bottom-bar `Failed` status.
    UpdateInstallFailed {
        error: String,
    },
}

/// Phase markers for cache prime / lazy loads. `Tables` carries the
/// (catalog, schema) so the UI can scope its re-render; `Columns`
/// carries the table identity so the popover can decide whether the
/// fresh data matches its current qualifier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CacheStage {
    DefaultSchema,
    Catalogs,
    Schemas {
        catalog: String,
    },
    Tables {
        catalog: String,
        schema: String,
    },
    Columns {
        catalog: String,
        schema: String,
        table: String,
    },
    Reloaded,
}

#[derive(Debug)]
pub enum SchemaPayload {
    Catalogs(Vec<CatalogInfo>),
    Schemas(Vec<SchemaInfo>),
    Tables(Vec<TableInfo>),
    Columns(Vec<ColumnInfo>),
    Indices(Vec<IndexInfo>),
}

/// Runs until either the command channel closes or `Close` is received.
/// Starts with no active datasource — the App is expected to send `Connect`
/// once the user has chosen one.
pub async fn run(
    logger: Logger,
    mut commands: UnboundedReceiver<WorkerCommand>,
    events: UnboundedSender<WorkerEvent>,
    cache: Arc<RwLock<SchemaCache>>,
) {
    let mut datasource: Option<Arc<dyn Datasource>> = None;
    let mut current_query: Option<JoinHandle<()>> = None;

    while let Some(cmd) = commands.recv().await {
        match cmd {
            WorkerCommand::Close => break,
            WorkerCommand::Connect { name, url } => {
                handle_connect(&logger, &events, &mut datasource, name, url).await;
            }
            WorkerCommand::Cancel => match &datasource {
                Some(ds) => cancel_query(&logger, ds.as_ref(), &mut current_query).await,
                None => logger.warn("worker", "cancel ignored: no active connection"),
            },
            WorkerCommand::Execute { req, sql } => match &datasource {
                Some(ds) => spawn_query(ds, &events, &mut current_query, req, sql),
                None => {
                    let _ = events.send(WorkerEvent::QueryFailed {
                        req,
                        error: DatasourceError::Connect("no active connection".into()),
                    });
                }
            },
            WorkerCommand::Introspect { target } => match &datasource {
                Some(ds) => spawn_introspect(ds, &events, target),
                None => {
                    let _ = events.send(WorkerEvent::SchemaFailed {
                        target,
                        error: DatasourceError::Connect("no active connection".into()),
                    });
                }
            },
            WorkerCommand::PrimeCompletionCache { connection } => match &datasource {
                Some(ds) => spawn_prime_cache(ds, &events, cache.clone(), connection, false),
                None => logger.warn("worker", "prime ignored: no active connection"),
            },
            WorkerCommand::Reload { connection } => match &datasource {
                Some(ds) => spawn_prime_cache(ds, &events, cache.clone(), connection, true),
                None => logger.warn("worker", "reload ignored: no active connection"),
            },
            WorkerCommand::LoadCompletionColumns {
                catalog,
                schema,
                table,
            } => match &datasource {
                Some(ds) => {
                    spawn_load_columns(ds, &events, cache.clone(), catalog, schema, table);
                }
                None => logger.warn("worker", "column load ignored: no active connection"),
            },
        }
    }
}

async fn handle_connect(
    logger: &Logger,
    events: &UnboundedSender<WorkerEvent>,
    current: &mut Option<Arc<dyn Datasource>>,
    name: String,
    url: String,
) {
    logger.info("worker", format!("connect to {name}"));
    match crate::datasource::connect(&url, logger.clone()).await {
        Ok(new_ds) => {
            // Drop the previous datasource — sqlx's pool closes on drop. We
            // can't call `Datasource::close` on an `Arc<dyn …>` cleanly, and
            // nothing today depends on graceful close.
            *current = Some(Arc::from(new_ds));
            let _ = events.send(WorkerEvent::Connected { name });
        }
        Err(error) => {
            logger.warn("worker", format!("connect failed: {error}"));
            let _ = events.send(WorkerEvent::ConnectFailed { name, error });
        }
    }
}

async fn cancel_query(
    logger: &Logger,
    datasource: &dyn Datasource,
    current: &mut Option<JoinHandle<()>>,
) {
    // Hit the server cancel first so the in-flight query's pinned connection
    // returns a "canceled" error of its own. Awaiting here also serializes
    // against the next command — no follow-up `Execute` can start and
    // overwrite the in-flight identifier before `cancel()` reads it.
    if let Err(e) = datasource.cancel().await {
        logger.warn("worker", format!("cancel failed: {e}"));
    }
    // Belt-and-braces: if the spawn_query future hasn't already finished
    // off the cancel error, drop it now so its pooled connection is freed.
    if let Some(handle) = current.take() {
        handle.abort();
    }
}

fn spawn_query(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    current: &mut Option<JoinHandle<()>>,
    req: RequestId,
    sql: String,
) {
    if let Some(prev) = current.take() {
        prev.abort();
    }
    let datasource = datasource.clone();
    let events = events.clone();
    *current = Some(tokio::spawn(async move {
        let event = handle_execute(datasource.as_ref(), req, sql).await;
        let _ = events.send(event);
    }));
}

fn spawn_introspect(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    target: IntrospectTarget,
) {
    let datasource = datasource.clone();
    let events = events.clone();
    tokio::spawn(async move {
        let event = handle_introspect(datasource.as_ref(), target).await;
        let _ = events.send(event);
    });
}

async fn handle_execute(datasource: &dyn Datasource, req: RequestId, sql: String) -> WorkerEvent {
    match datasource.execute(&sql).await {
        Ok(result) => WorkerEvent::QueryDone { req, result },
        Err(error) => WorkerEvent::QueryFailed { req, error },
    }
}

fn spawn_load_columns(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    cache: Arc<RwLock<SchemaCache>>,
    catalog: String,
    schema: String,
    table: String,
) {
    let datasource = datasource.clone();
    let events = events.clone();
    tokio::spawn(async move {
        load_columns(datasource.as_ref(), &events, &cache, catalog, schema, table).await;
    });
}

async fn load_columns(
    datasource: &dyn Datasource,
    events: &UnboundedSender<WorkerEvent>,
    cache: &RwLock<SchemaCache>,
    catalog: String,
    schema: String,
    table: String,
) {
    // If another caller already populated this entry while we were
    // queued, skip the round-trip. The check is racy (a second
    // identical load could still get through), but the worst case is a
    // duplicated read — acceptable for an autocomplete prime.
    if let Ok(guard) = cache.read()
        && guard
            .columns
            .contains_key(&(catalog.clone(), schema.clone(), table.clone()))
    {
        return;
    }
    match datasource
        .introspect_columns(&catalog, &schema, &table)
        .await
    {
        Ok(cols) => {
            let cached: Vec<CachedColumn> = cols
                .into_iter()
                .map(|c| CachedColumn {
                    name: c.name,
                    type_name: c.type_name,
                })
                .collect();
            if let Ok(mut guard) = cache.write() {
                guard
                    .columns
                    .insert((catalog.clone(), schema.clone(), table.clone()), cached);
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Columns {
                    catalog,
                    schema,
                    table,
                },
            });
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::Columns {
                    catalog,
                    schema,
                    table,
                },
                error,
            });
        }
    }
}

fn spawn_prime_cache(
    datasource: &Arc<dyn Datasource>,
    events: &UnboundedSender<WorkerEvent>,
    cache: Arc<RwLock<SchemaCache>>,
    connection: String,
    is_reload: bool,
) {
    let datasource = datasource.clone();
    let events = events.clone();
    tokio::spawn(async move {
        prime_cache(datasource.as_ref(), &events, &cache, connection, is_reload).await;
    });
}

/// Phase 1 cache prime: default schema + catalogs + schemas of the
/// default catalog + tables of the default schema. Each step writes its
/// result into the shared cache and emits a `CompletionCacheStage`
/// event. Failures are logged via `CompletionCacheFailed` but don't
/// abort later stages — partial data is more useful than none.
async fn prime_cache(
    datasource: &dyn Datasource,
    events: &UnboundedSender<WorkerEvent>,
    cache: &RwLock<SchemaCache>,
    connection: String,
    is_reload: bool,
) {
    if is_reload && let Ok(mut guard) = cache.write() {
        guard.clear();
    }

    // Stage 1: default schema. If this fails we still try the rest, but
    // unqualified contexts won't have anywhere to look.
    let default = match datasource.default_schema().await {
        Ok(d) => {
            if let Ok(mut guard) = cache.write() {
                guard.connection = Some(connection.clone());
                guard.default_catalog = Some(d.catalog.clone());
                guard.default_schema = Some(d.schema.clone());
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::DefaultSchema,
            });
            Some(d)
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::DefaultSchema,
                error,
            });
            None
        }
    };

    // Stage 2: catalogs.
    match datasource.introspect_catalogs().await {
        Ok(catalogs) => {
            if let Ok(mut guard) = cache.write() {
                guard.catalogs = catalogs.iter().map(|c| c.name.clone()).collect();
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Catalogs,
            });
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::Catalogs,
                error,
            });
        }
    }

    // Stage 3+4 only run if we know where to look.
    let Some(default) = default else {
        if is_reload {
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Reloaded,
            });
        }
        return;
    };

    // Stage 3: schemas of the default catalog.
    match datasource.introspect_schemas(&default.catalog).await {
        Ok(schemas) => {
            if let Ok(mut guard) = cache.write() {
                guard.schemas.insert(
                    default.catalog.clone(),
                    schemas.iter().map(|s| s.name.clone()).collect(),
                );
            }
            let _ = events.send(WorkerEvent::CompletionCacheStage {
                stage: CacheStage::Schemas {
                    catalog: default.catalog.clone(),
                },
            });
        }
        Err(error) => {
            let _ = events.send(WorkerEvent::CompletionCacheFailed {
                stage: CacheStage::Schemas {
                    catalog: default.catalog.clone(),
                },
                error,
            });
        }
    }

    // Stage 4: tables of the default schema. (Columns are lazy.)
    if !default.schema.is_empty() {
        match datasource
            .introspect_tables(&default.catalog, &default.schema)
            .await
        {
            Ok(tables) => {
                let cached: Vec<CachedTable> = tables
                    .into_iter()
                    .map(|t| CachedTable {
                        name: t.name,
                        kind: t.kind,
                    })
                    .collect();
                if let Ok(mut guard) = cache.write() {
                    guard
                        .tables
                        .insert((default.catalog.clone(), default.schema.clone()), cached);
                }
                let _ = events.send(WorkerEvent::CompletionCacheStage {
                    stage: CacheStage::Tables {
                        catalog: default.catalog.clone(),
                        schema: default.schema.clone(),
                    },
                });
            }
            Err(error) => {
                let _ = events.send(WorkerEvent::CompletionCacheFailed {
                    stage: CacheStage::Tables {
                        catalog: default.catalog.clone(),
                        schema: default.schema.clone(),
                    },
                    error,
                });
            }
        }
    }

    if is_reload {
        let _ = events.send(WorkerEvent::CompletionCacheStage {
            stage: CacheStage::Reloaded,
        });
    }
}

async fn handle_introspect(datasource: &dyn Datasource, target: IntrospectTarget) -> WorkerEvent {
    let outcome = match &target {
        IntrospectTarget::Catalogs => datasource
            .introspect_catalogs()
            .await
            .map(SchemaPayload::Catalogs),
        IntrospectTarget::Schemas { catalog } => datasource
            .introspect_schemas(catalog)
            .await
            .map(SchemaPayload::Schemas),
        IntrospectTarget::Tables { catalog, schema } => datasource
            .introspect_tables(catalog, schema)
            .await
            .map(SchemaPayload::Tables),
        IntrospectTarget::Columns {
            catalog,
            schema,
            table,
        } => datasource
            .introspect_columns(catalog, schema, table)
            .await
            .map(SchemaPayload::Columns),
        IntrospectTarget::Indices {
            catalog,
            schema,
            table,
        } => datasource
            .introspect_indices(catalog, schema, table)
            .await
            .map(SchemaPayload::Indices),
    };
    match outcome {
        Ok(payload) => WorkerEvent::SchemaLoaded { target, payload },
        Err(error) => WorkerEvent::SchemaFailed { target, error },
    }
}
